#!/bin/bash

for i in 1 2 3 4 5 6 7 8 9 0 ; do
  echo "`date` i=$i ..."

  /bin/cat /vsys/vif_down.out &
  CAT_PID=$!
  echo "   -> Waiting for $CAT_PID ..."
  
  (
     echo "tun506-$i"
     echo "delete=1"
  ) >/vsys/vif_down.in
  
  wait $CAT_PID

done
