#!/bin/bash
# $Id$
#
# Simple Connectivity Test
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

set -e

. ./tunnel-setup


SliceID=506
LocalIP=169.254.100.81
TunnelBoxNorth=169.254.100.71
TunnelBoxSouth=169.254.100.70

make-planetlab-tunnel tun$SliceID-1 $SliceID 0x28 $LocalIP $TunnelBoxNorth 10.100.1.4 10.100.1.3 default
make-planetlab-tunnel tun$SliceID-2 $SliceID 0x48 $LocalIP $TunnelBoxSouth 172.16.1.4 172.16.1.3 default


# It is probably a good idea to set the DSCP to 0 here. Then, its setting will
# not interfere with routers within the core network. The ECN bits will be
# left untouched.
#iptables -t mangle -A POSTROUTING -j TOS --set-tos 0x00/0xfc

# Turn on ECN for TCP.
#sysctl net.ipv4.tcp_ecn=1
