#!/bin/bash
# $Id$
#
# Simple Connectivity Test
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

set -e

. ./tunnel-setup


TunnelBox=132.252.156.71


# Development Machines
RemoteIP=132.252.156.51
make-tunnel gre1 256 0x00 $TunnelBox $RemoteIP 10.100.1.1 10.100.1.2 ""

RemoteIP=132.252.156.52
make-tunnel gre2 258 0x00 $TunnelBox $RemoteIP 10.100.2.1 10.100.2.2 ""


# Crossconnect
RemoteTunnelBox=132.252.156.70
make-tunnel gre3 512 0x00 $TunnelBox $RemoteTunnelBox 192.168.1.1 192.168.1.2 ""
ip route add 172.16.0.0/16 dev gre3

sysctl net.ipv4.ip_forward=1


# NorNet Nodes
SliceID=506
make-tunnel greN01 $SliceID 0x00 $TunnelBox 132.252.156.81 10.100.1.3 10.100.1.4 "" "csum"
make-tunnel greN02 $SliceID 0x00 $TunnelBox 132.252.156.82 10.100.1.5 10.100.1.6 "" "csum"
make-tunnel greN03 $SliceID 0x00 $TunnelBox 132.252.156.83 10.100.1.7 10.100.1.8 "" "csum"

make-tunnel greN04 $SliceID 0x00 $TunnelBox 132.252.156.84 10.100.1.9  10.100.1.10 "" "csum"
make-tunnel greN05 $SliceID 0x00 $TunnelBox 132.252.156.85 10.100.1.11 10.100.1.12 "" "csum"
make-tunnel greN06 $SliceID 0x00 $TunnelBox 132.252.156.86 10.100.1.13 10.100.1.14 "" "csum"
