#!/bin/bash

loop_couter=1
maximum_runs=2
host_name=$(cat /etc/rc.conf |grep hostname |cut -d '"' -f 2)


mkdir old
mkdir old/traceroute
mv traceroute*.txt old/traceroute/.

echo "old files moved to old/traceroute/"

file_name_path_unicom="traceroute_$host_name-1135910458.txt"
file_name_path_uninet="traceroute_$host_name-2103745148.txt"


path_unicom="$host_name-1135910458"
path_uninet="$host_name-2103745148"




while [ $loop_couter -ne 0 ] 
do
	echo "tracert number $loop_couter"
	date_value=$(date)
	traceroute_value=$(echo $(traceroute 113.59.104.58))
	line_value="$loop_couter $path_unicom $date_value $traceroute_value"
	echo $line_value >>$file_name_path_unicom


	date_value=$(date)
	traceroute_value=$(echo $(traceroute 210.37.45.148))
	line_value="$loop_couter $path_uninet $date_value $traceroute_value"
	echo $line_value >>$file_name_path_uninet

	echo "loop $loop_couter done, waiting"
	echo
	echo
	sleep 180

	loop_couter=$(( $loop_couter + 1 ))
done
