#!/bin/bash
# $Id: run-wp3-dsl-ccI 1140 2011-11-23 06:43:27Z dreibh $
#
# Network Performance Meter
# Copyright (C) 2009-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="haikou-cmt-DFN-unicom-mpctp-west-SP"
. ./measure-version2


Run_VALUES="1 2" # 3" # 4 5 6 7" #
Scenario_VALUES="haikou-cmt-DFN-unicom-mpctp-west-SP"
Runtime_VALUES="300"  #120 90
Flows_VALUES="1"
CompareWithReference_VALUES="false" # true"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll für Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
Unordered_VALUES="0.0"   # !!!
SndBuf_VALUES="5000 50000 100000 200000 300000 400000 500000 100000 500000 1000000 3000000 5000000 10000000 20000000"
RcvBuf_VALUES=-1
Protocol_VALUES="TCP SCTP"
CMTCCVariant_VALUES="off" #
OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="true"

# First trail
RateNorthernTrail_VALUES="50000" #
DelayNorthernTrail_VALUES="0" 
LossNorthernTrail_VALUES="0"


# Second trail
#RateSouthernTrail_VALUES="0"
#DelaySouthernTrail_VALUES="0"
#LossSouthernTrail_VALUES="0"
#QueueTypeSouthernTrail_VALUES="red"   ## !!!
# FrameCapacitySouthernTrail_VALUES="100"   ## !!!


perform_measurements
