#!/bin/sh -e
# ==========================================================================
#         _   _      _   ____            __ __  __      _
#        | \ | | ___| |_|  _ \ ___ _ __ / _|  \/  | ___| |_ ___ _ __
#        |  \| |/ _ \ __| |_) / _ \ '__| |_| |\/| |/ _ \ __/ _ \ '__|
#        | |\  |  __/ |_|  __/  __/ |  |  _| |  | |  __/ ||  __/ |
#        |_| \_|\___|\__|_|   \___|_|  |_| |_|  |_|\___|\__\___|_|
#
#                  NetPerfMeter -- Network Performance Meter
#                 Copyright (C) 2009-2024 by Thomas Dreibholz
# ==========================================================================
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact:  dreibh@simula.no
# Homepage: https://www.nntb.no/~dreibh/netperfmeter/

# Conversion of Dia to EPS and PDF:
dia -n -t eps-pango -e netperfmeter.eps logo/Logo-NetPerfMeter.dia
epstopdf --outfile=netperfmeter.pdf.tmp netperfmeter.eps
pdfcrop --hires netperfmeter.pdf.tmp netperfmeter.pdf
rm -f netperfmeter.pdf.tmp

# Conversion of PDF to PNG with alpha channel:
# * Add border of 1 pixel
# * Make color #eeeeee transparent (the background)
# * Crop the image, removing possibly non-transparent border lines
gm convert netperfmeter.pdf \
   -transparent "#eeeeee" -resize 514x -crop 512x512+1+1 -background \
   none -gravity center -extent 512x512 \
   netperfmeter.png

# Conversion of PDF to SVG:
pdf2svg netperfmeter.pdf netperfmeter.svg
