#!/bin/bash
# $Id: run-wp3-dsl-ccI 1140 2011-11-23 06:43:27Z dreibh $
#
# Network Performance Meter
# Copyright (C) 2009-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="haikou-Disjoint-local-Essen-MPTCP-Dissimilar"
. ./measure-version2

Run_VALUES="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23" #  24" # 25 26 27 28 29" # 30 31 32 33 34 35 36 37 39 40 41 42 43 44 45 46 47 48 49 50" 
Scenario_VALUES="MPCTP-West_MPCTP-east-MPTCP-Ubuntu"
Runtime_VALUES="300"
Flows_VALUES="1"
CompareWithReference_VALUES="false" # true"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll für Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
Unordered_VALUES="0.0"   # !!!

SndBuf_VALUES="6000000" 
RcvBuf_VALUES=-1

Protocol_VALUES="TCP"
CMTCCVariant_VALUES="off"

OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="false"

# First trail
#RateNorthernTrail_VALUES="200 800 1000 2001 3001 4001 5000 6000 7001 8001 9001 10000"
RateNorthernTrail_VALUES="200 500 800 1000 1250 1500  1750 2001 2250  2500 2750 3000" # 4001 5000 6000 7001 8001 9001 10000"

DelayNorthernTrail_VALUES="200" # 

# Second trail
RateSouthernTrail_VALUES="800"



perform_measurements

