#!/bin/bash
# $Id: run-wp3-dsl-ccI 1140 2011-11-23 06:43:27Z dreibh $
#
# Network Performance Meter
# Copyright (C) 2009-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

Directory="haikou-mptcp-throughputI"
. ./measure-version2


Run_VALUES="1"
Scenario_VALUES="haikou-mptcp"
Runtime_VALUES="20" #"300" 
Flows_VALUES="1"
CompareWithReference_VALUES="false"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll für Referenzstrom
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
SndBuf_VALUES="100000"
RcvBuf_VALUES="100000"
Protocol_VALUES="TCP"
#CMTCCVariant_VALUES="off"

BidirectionalQoS_VALUES="true"

# First trail
RateNorthernTrail_VALUES="2000 5000" 
DelayNorthernTrail_VALUES="0" 
LossNorthernTrail_VALUES="0"
#QueueTypeNorthernTrail_VALUES="red"      ## !!!
#FrameCapacityNorthernTrail_VALUES="100"   ## !!!

# Second trail
RateSouthernTrail_VALUES="0"
DelaySouthernTrail_VALUES="0"
LossSouthernTrail_VALUES="0"



perform_measurements
