#!/usr/bin/env bash

REMOTE=localhost:9000

TCP_FLOWS=5
TCP_PARAMS="const0:const0:const0:const1460:cmt=off"

UDP_FLOWS=5
UDP_PARAMS="const0:const0:const25:const2500:onoff=+pareto0.166667,1.5,+pareto0.166667,1.5,repeat"


options=""
i=0 ; while [ $i -lt $TCP_FLOWS ] ; do
   options="$options -tcp $TCP_PARAMS"
   let i=$i+1
done
i=0 ; while [ $i -lt $UDP_FLOWS ] ; do
   options="$options -udp $UDP_PARAMS"
   let i=$i+1
done

echo "OPTIONS=$options"
# make -j2 && ./
netperfmeter $REMOTE $options
