.\" ==========================================================================
.\"         _   _      _   ____            __ __  __      _
.\"        | \ | | ___| |_|  _ \ ___ _ __ / _|  \/  | ___| |_ ___ _ __
.\"        |  \| |/ _ \ __| |_) / _ \ '__| |_| |\/| |/ _ \ __/ _ \ '__|
.\"        | |\  |  __/ |_|  __/  __/ |  |  _| |  | |  __/ ||  __/ |
.\"        |_| \_|\___|\__|_|   \___|_|  |_| |_|  |_|\___|\__\___|_|
.\"
.\"                  NetPerfMeter -- Network Performance Meter
.\"                 Copyright (C) 2009-2026 by Thomas Dreibholz
.\" ==========================================================================
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact:  dreibh@simula.no
.\" Homepage: https://www.nntb.no/~dreibh/netperfmeter/
.\"
.\" ###### Setup ############################################################
.Dd November 11, 2025
.Dt createsummary 1
.Os CreateSummary
.\" ###### Name #############################################################
.Sh NAME
.Nm createsummary
.Nd Scalar File Summarisation Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm createsummary
.Op variable_names
.br
.Op Fl b | Fl Fl batch | Fl i | Fl Fl interactive
.br
.Op Fl l | Fl Fl line-numbers | Fl n | Fl Fl no-line-numbers
.br
.Op Fl s | Fl Fl split | Fl a | Fl Fl no-split
.br
.Op Fl c Ar level | Fl Fl compress Ar level
.br
.Op Fl r | Fl Fl ignore-scalar-file-errors
.br
.Op Fl q | Fl Fl quiet
.Nm createsummary
.Op Fl h | Fl Fl help
.Nm createsummary
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm createsummary
is a summarisation tool for scalar files: it creates one CSV/GNU R data table file (using tabulator as column separator) for each scalar. CreateSummary supports on-the-fly BZip2 compression. After startup, the program accepts the following commands from standard input (*not* as command-line arguments!):
.Bl -tag -width indent
.It Fl Fl varnames=variables
A space-separated list of output variable names to be added to the output data tables.
.It Fl Fl values=values
Sets the values of the output variables for the next scalar file to the provided space-separated values. One value for each variable has to be provided.
.It Fl Fl input=filename
Process the given scalar file.
.It Fl Fl logfile=name
Sets the log file for the next scalar file. On an error related to this scalar file, the log file's name is displayed. This option can be used to identify bad simulation/measurement runs by pointing to the log file being created for
the simulation/measurement.
.It Fl Fl statusfile=name
Sets the status file for the next scalar file. On an error related to this scalar file, the status file is deleted. This option can be used to repeat bad simulation/measurement runs by re-running the simulation/measurement on missing status files.
.It Fl Fl skip=prefix
All scalars beginning with the given prefix are not written to output tables. This option can be used to filter out unnecessary results.
.It Fl Fl simulationdirectory=directory
Sets the directory where to find the scalar files.
.It Fl Fl resultsdirectory=directory
Sets the directory where to write the summary tables to.
.It Fl Fl ignore-scalar-file-errors
Ignore scalar file errors (that is, missing input files) instead of aborting.
.El
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It variable_names
A space-separated list of output variable names to be added to the output data tables.
.It Fl b | Fl Fl batch
Run in batch mode. The program is aborted on errors.
.It Fl i | Fl Fl interactive
Run in interactive mode (default). On errors, the program is continued.
.It Fl l | Fl Fl line-numbers
Add line numbers into the output table files, as usual for GNU R.
.It Fl n | Fl Fl no-line-numbers
Do not add line numbers into the output table files, as usual for CSV (default).
.It Fl s | Fl Fl split
Try to split the scalar name ending in a number into the name part as well as the number. A scalar output table is then generated for the name part, with the corresponding number in table column "Split". Example: Scalars "Throughput1", ..., "Throughput9" will be written into output table "Throughput", the number will be in table column "Split". Without the \-\-split option, each scalar would get its own table.
.It Fl a | Fl Fl no-split
Turns scalar splitting off (default).
.It Fl c Ar level | Fl Fl compress Ar level
Sets the BZip2 compression level; 1=none, 9=highest (default).
.It Fl r | Fl Fl ignore-scalar-file-errors
Ignore scalar file errors (that is, missing input files) instead of aborting.
.It Fl q | Fl Fl quiet
Do not print verbose status information.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLE
Consider two simulation results
test1.sca.bz2 (created with ParameterX=One) and
test2.sca.bz2 (created with ParameterX=Two). The scalar files are located in
the current directory, the output tables should be written to /tmp with
compression level 5:
.br
( echo "\-\-simulationsdirectory=."  && \\
  echo "\-\-resultsdirectory=/tmp"   && \\
  echo "\-\-values=One"              && \\
  echo "\-\-input=test1.sca.bz2"     && \\
  echo "\-\-values=Two"              && \\
  echo "\-\-input=test2.sca.bz2" ) | createsummary "ParameterX" \-\-batch \-\-compress 5
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/netperfmeter
.br
mailto://dreibh@simula.no
.br
