#!/bin/bash -e

TARGET="$1"
if [ "$TARGET" == "" ] ; then
   TARGET="localhost:9000"
fi

./netperfmeter $TARGET -vector=f.vec -scalar=f.sca \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -dccp const80:const10000:const80:const10000 \
   -runtime=10
