#!/bin/sh -e

TARGET="$1"
if [ "$TARGET" == "" ] ; then
   TARGET="localhost:9000"
fi

./netperfmeter $TARGET -vector=f.vec -scalar=f.sca \
   -sctp \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
     const8:const10000:const8:const10000 \
   -runtime=10
