.\" Get current time stamp
.\" Copyright (C) 2018-2024 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd April 20, 2017
.Dt getabstime 1
.Os getabstime
.\" ###### Name #############################################################
.Sh NAME
.Nm getabstime
.Nd Get Current Time Stamp
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm getabstime
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm getabstime
prints the current 64-bit time stamp (microseconds since the epoch).
.Pp
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
http://simula.no/people/dreibh
.br
mailto://dreibh@simula.no
.br
