#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2011 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

DESTINATION=kerneltests
if [ $# -ge 1 ] ; then
   DESTINATION="$1"
fi

# ------ List test scripts here ---------------------------
# Test script naming: $TEST -> run-$TEST and plot-$TEST.R
# Corresponding results directory name: $TEST
ALL_TESTS="wp0-cmt-throughputI wp1-rp-disjointPathsI wp1-rp-sharedBottleneckI"

# ------ Enter kernel sources directory here --------------
KERNEL_SRC_DIRECTORY="$HOME/src/KERN"


# ====== Create destination directory =======================================
if [ ! -e $DESTINATION ] ; then
   echo >&2 "ERROR: Destination directory $DESTINATION does not exist!"
   exit 1
fi

TIMESTAMP="`date +"%Y%m%d-%H%M%S"`"
TEMPRESULTSDIR="/tmp/$TIMESTAMP-KernelTest"
FINALRESULTSDIR="$DESTINATION/$TIMESTAMP-KernelTest"
mkdir $TEMPRESULTSDIR


# ====== Run tests ==========================================================
for myTest in $ALL_TESTS ; do
   echo ""
   echo "###### Running test \"$myTest\" on `env LANG=C date` ######"
   echo ""
   if [ -e $myTest.old ] ; then
      rm -rf $myTest.old
   fi
   if [ -e $myTest ] ; then
      mv $myTest $myTest.old
   fi
   ./run-$myTest && \
   ./archive-measurement $myTest && \
   cp $myTest.pdf $myTest.tar.bz2 $myTest-complete.tar.bz2 $TEMPRESULTSDIR
done


# ====== Archive kernel =====================================================
echo ""
echo "###### Archiving kernel to kernel-$TIMESTAMP.tar.bz2 ######"
echo ""
tar cjf $TEMPRESULTSDIR/kernel-$TIMESTAMP.tar.bz2 -C $HOME/src/KERN . || exit 1


# ====== Move results to final destination ==================================
mv $TEMPRESULTSDIR $FINALRESULTSDIR
rm -f $DESTINATION/LATEST
ln -s $TIMESTAMP-KernelTest $DESTINATION/LATEST
echo ""
echo "###### Results have been stored in $FINALRESULTSDIR ######"
