#!/bin/sh -eu

make netperfmeter
netperfmeter 9000 \
   -tls-hostname "$(hostname -f)" \
   -tls-ca       "$DIRECTORY/TestCA/TestLevel1/certs/TestLevel1.crt"
   -quic const10:const128:const25:const1200
