.\" ==========================================================================
.\"         _   _      _   ____            __ __  __      _
.\"        | \ | | ___| |_|  _ \ ___ _ __ / _|  \/  | ___| |_ ___ _ __
.\"        |  \| |/ _ \ __| |_) / _ \ '__| |_| |\/| |/ _ \ __/ _ \ '__|
.\"        | |\  |  __/ |_|  __/  __/ |  |  _| |  | |  __/ ||  __/ |
.\"        |_| \_|\___|\__|_|   \___|_|  |_| |_|  |_|\___|\__\___|_|
.\"
.\"                  NetPerfMeter -- Network Performance Meter
.\"                 Copyright (C) 2009-2025 by Thomas Dreibholz
.\" ==========================================================================
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact:  dreibh@simula.no
.\" Homepage: https://www.nntb.no/~dreibh/netperfmeter/
.\"
.\" ###### Setup ############################################################
.Dd October 18, 2024
.Dt pdfembedfonts 1
.Os pdfembedfonts
.\" ###### Name #############################################################
.Sh NAME
.Nm pdfembedfonts
.Nd PDF Metadata Updater
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm pdfembedfonts
input_pdf
output_pdf
.Op Fl optimize
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm pdfembedfonts
uses GhostScript to make a copy of a given PDF file, embedding all
required font data. Optionally, the resulting PDF can also be optimized
("fast web view", "linearized").
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments have to be provided:
.Bl -tag -width indent
.It input_pdf
The input PDF file name.
.It output_pdf
The output PDF file name.
.It Fl optimize
Optimize the resulting PDF file for fast web view.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
A pdfembedfonts usage example:
.Bl -tag -width indent
.It pdfembedfonts MyDocument.pdf MyDocument-with-Embedded-Fonts.pdf
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/netperfmeter
.br
mailto://dreibh@simula.no
.br
