#!/bin/sh

Bandwidth=50000
Delay=1
Loss=0
Error=0
Bidirectional=true
OptionCMT=on
OptionRP=off
OptionDAC=on
OptionNRSACK=off

echo WEST:
                   ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setsctp cmt $OptionCMT dac $OptionDAC nrsack $OptionNRSACK rp $OptionRP
echo EAST:
ssh 132.252.153.18 ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setsctp cmt $OptionCMT dac $OptionDAC nrsack $OptionNRSACK rp $OptionRP

echo NORTH:
ssh 132.252.153.9   ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setqos 1 132.252.153.8/29 132.252.153.16/29    $Bandwidth $Delay $Loss $Error $Bidirectional
echo SOUTH:
ssh 132.252.153.137 ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setqos 1 132.252.153.136/29 132.252.153.144/29 $Bandwidth $Delay $Loss $Error $Bidirectional
