#!/bin/sh

OptionCMT=on
OptionRP=off
OptionDAC=on
OptionNRSACK=on

echo WEST:
                   ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setsctp cmt $OptionCMT dac $OptionDAC nrsack $OptionNRSACK rp $OptionRP
echo EAST:
ssh 132.252.153.18 ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setsctp cmt $OptionCMT dac $OptionDAC nrsack $OptionNRSACK rp $OptionRP
