#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="wp1-cc-disjoint-bandwidth-betaI"
. ./measure-version2


Run_VALUES="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15"   ## Hier Run-Nummern angeben, z.B. "1 2 3 4 5".
Scenario_VALUES="DisjointPaths"
Runtime_VALUES="300" ##"300"   # !!!
Flows_VALUES="1"
CompareWithReference_VALUES="true"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll fuer Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1452"
Unordered_VALUES="1.0"   # !!!
SndBuf_VALUES="5000000" ##"5000000"
RcvBuf_VALUES="5000000" ##"1000000" ##"5000000"
CMTCCVariant_VALUES="cmt cmtrpv1 cmtrpv2 like-mptcp"
#CMTCCVariant_VALUES="cmt"
OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="true"

# First trail
#RateNorthernTrail_VALUES="500 1000 2000 3000 4000 5000 7000" ##10000" ## 13000 15000"
RateNorthernTrail_VALUES="1000 2000 3000 4000 5000 6000 7000 8000 9000" ## 10000"

DelayNorthernTrail_VALUES="10" ##"10"
LossNorthernTrail_VALUES="0"
QueueTypeNorthernTrail_VALUES="red"      ## !!!
FrameCapacityNorthernTrail_VALUES="100"   ## !!!

# Second trail
RateSouthernTrail_VALUES="2500" ##"1000"
DelaySouthernTrail_VALUES="10" ##"10"
LossSouthernTrail_VALUES="0"
QueueTypeSouthernTrail_VALUES="red"   ## !!!
FrameCapacitySouthernTrail_VALUES="100"   ## !!!


perform_measurements
