#!/bin/bash

HOST_EAST="132.252.153.18"
HOST_WEST="132.252.153.10,132.252.153.138"
ROUTER_NORTH="132.252.153.9"
NETWORK_NW="132.252.153.8/29"
NETWORK_NE="132.252.153.16/29"
ROUTER_SOUTH="132.252.153.137"
NETWORK_SW="132.252.153.136/29"
NETWORK_SE="132.252.153.144/29"

LocalOpts="-local=$HOST_WEST"
RemoteNode="$HOST_EAST:9000"


Run="1"
Runtime="60"
Flows="1"
OnlyOneAssoc="true"
FrameRate="const0"
FrameSize="const1452"
Unordered="1.0"
SndBuf="15000"
RcvBuf="15000"
OptionCMT="true"
OptionDAC="true"
OptionNRSACK="true"
RateNorthernTrail="1000"
DelayNorthernTrail="0"
LossNorthernTrail="0"
RateSouthernTrail="1000"
DelaySouthernTrail="0"
LossSouthernTrail="0"


~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setsctp cmt $OptionCMT dac $OptionDAC nrsack $OptionNRSACK || exit 1
ssh $HOST_EAST ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setsctp cmt $OptionCMT dac $OptionDAC nrsack $OptionNRSACK || exit 1
ssh $ROUTER_NORTH ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setqos 1 $NETWORK_NW $NETWORK_NE $RateNorthernTrail $DelayNorthernTrail $LossNorthernTrail || exit 1
ssh $ROUTER_SOUTH ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setqos 1 $NETWORK_SW $NETWORK_SE $RateSouthernTrail $DelaySouthernTrail $LossSouthernTrail || exit 1


# ====== NetPerfMeter run =============================================
runDirectory="."
runScalar="$runDirectory/output.sca"
runVector="$runDirectory/output.vec"
runConfig="$runDirectory/output.config"

command="./netperfmeter $RemoteNode"
command="$command -scalar=$runScalar"
command="$command -vector=$runVector"
command="$command -config=$runConfig"
command="$command -runtime=$Runtime"

n=0
id=1
command="$command -sctp "
while [ $n -lt $Flows ] ; do
   command="$command $FrameRate:$FrameSize:const0:const0:id=$id:unordered=$Unordered:sndbuf=$SndBuf:rcvbuf=$RcvBuf "
   let n=$n+1
   let id=$id+1
done


echo "====================================================="
echo $command
echo "====================================================="

$command
