#!/bin/bash
# $Id: run-wp3-dsl-ccI 1140 2011-11-23 06:43:27Z dreibh $
#
# Network Performance Meter
# Copyright (C) 2009-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="haikou-Disjoint-local-Essen"
. ./measure-version2


Run_VALUES="1 2" # 3 4 5" # 6 7 8"
Scenario_VALUES="DisjointPaths"
Runtime_VALUES="90" 
Flows_VALUES="1"
CompareWithReference_VALUES="false" # true"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll für Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
Unordered_VALUES="0.0"   # !!!
SndBuf_VALUES="5000 50000 100000 300000 500000 1000000 1500000 2000000 2500000"
RcvBuf_VALUES=-1
CMTCCVariant_VALUES="like-mptcp" #cmt 
OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="true"

# First trail
#RateNorthernTrail_VALUES="200 5000 50000 70000 100000 150000 200000 300000" 
RateNorthernTrail_VALUES="70000" 
DelayNorthernTrail_VALUES="0 10 50 200"
#DelayNorthernTrail_VALUES="0"
LossNorthernTrail_VALUES="0"


perform_measurements

