#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2011 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="wp3-dsl-ccII"
. ./measure-version2


Run_VALUES="1 2 3 4"
Scenario_VALUES="Burgsteinfurt"
Runtime_VALUES="60"   # !!!
Flows_VALUES="1"
CompareWithReference_VALUES="true"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll für Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
Unordered_VALUES="1.0"   # !!!
SndBuf_VALUES="1000000"
RcvBuf_VALUES="500000"
# CMTCCVariant_VALUES="cmtrpv2"
CMTCCVariant_VALUES="cmt cmtrpv2 like-mptcp" # cmtrpv1 cmtrpv2 like-mptcp"
OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="true"

# First trail
RateNorthernTrail_VALUES="200 250 300 350 400 800 1000 2000"
DelayNorthernTrail_VALUES="28"
LossNorthernTrail_VALUES="0"
QueueTypeNorthernTrail_VALUES="red"      ## !!!
FrameCapacityNorthernTrail_VALUES="100"   ## !!!

# Second trail
RateSouthernTrail_VALUES="0"
DelaySouthernTrail_VALUES="0"
LossSouthernTrail_VALUES="0"
QueueTypeSouthernTrail_VALUES="fifo"   ## !!!
# FrameCapacitySouthernTrail_VALUES="100"   ## !!!


perform_measurements
