#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="test8"
. ./measure-version2


Run_VALUES="1 2 3 4 5 6 7 8"
Scenario_VALUES="Burgsteinfurt"
Runtime_VALUES="60"
Flows_VALUES="1"
ReferenceFlows_VALUES="1"
CompareWithReference_VALUES="true"
ReferenceFlowProtocol_VALUES="TCP"   ## !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Protokoll für Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
Unordered_VALUES="1.0"   # !!!
SndBuf_VALUES="1000000"
RcvBuf_VALUES="500000"
CMTCCVariant_VALUES="cmt cmtrpv2 like-mptcp"   # cmt cmtrpv1 cmtrpv2 like-mptcp 
OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="true"

# First trail
RateNorthernTrail_VALUES="800 10000 15000 20000"
DelayNorthernTrail_VALUES="0"
LossNorthernTrail_VALUES="0"
QueueTypeNorthernTrail_VALUES="fifo"      ## !!!
#FrameCapacityNorthernTrail_VALUES="20"   ## !!!

# RedMinThNorthernTrail_VALUES="30"
# RedMaxThNorthernTrail_VALUES="90"
# RedMaxPNorthernTrail_VALUES="0.02"
# RedWqNorthernTrail_VALUES="0.002"


# Second trail
# RateSouthernTrail_VALUES="800"
# DelaySouthernTrail_VALUES="28"
# LossSouthernTrail_VALUES="0"
# QueueTypeSouthernTrail_VALUES="fifo"      ## !!!
# FrameCapacitySouthernTrail_VALUES="100"   ## !!!


perform_measurements
