#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2010 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

. ./measure-version1

Directory="TEST3"

Run_VALUES="1 2 3 4 5 6"
Runtime_VALUES="60"
Flows_VALUES="1"
CompareWithReference_VALUES="true"
ReferenceFlowProtocol_VALUES="TCP"
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1452"
Unordered_VALUES="1.0"   # !!!
SndBuf_VALUES="12500000"
RcvBuf_VALUES="12500000"
OptionCMT_VALUES="true"
OptionRP_VALUES="false true"
OptionDAC_VALUES="true"
OptionNRSACK_VALUES="true"

# First trail
RateNorthernTrail_VALUES="10000 25000 40000 50000"
DelayNorthernTrail_VALUES="0"
LossNorthernTrail_VALUES="0"
# Second trail
RateSouthernTrail_VALUES="-1"
DelaySouthernTrail_VALUES="-1"
LossSouthernTrail_VALUES="-1"

perform_measurements
