#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2011 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="wp3-dsl-ccI"
. ./measure-version2


Run_VALUES="1"
Scenario_VALUES="DisjointPaths"
Runtime_VALUES="60"
Flows_VALUES="1"
CompareWithReference_VALUES="false"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll für Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # DSL-MTU!
Unordered_VALUES="1.0"   # !!!
SndBuf_VALUES="1000000"
RcvBuf_VALUES="500000"
CMTCCVariant_VALUES="cmt cmtrpv1"
OptionNRSACK_VALUES="true"
OptionBufferSplitting_VALUES="bothSides"

BidirectionalQoS_VALUES="true"
CwndMaxBurst_VALUES="true"

# First trail
RateNorthernTrail_VALUES="800 20000"
DelayNorthernTrail_VALUES="50"
LossNorthernTrail_VALUES="0"
QueueTypeNorthernTrail_VALUES="fifo"      ## !!!
FrameCapacityNorthernTrail_VALUES="10"   ## !!!

# Second trail
RateSouthernTrail_VALUES="800"
DelaySouthernTrail_VALUES="26"
LossSouthernTrail_VALUES="0"
QueueTypeSouthernTrail_VALUES="fifo"   ## !!!
FrameCapacityNorthernTrail_VALUES="100"   ## !!!


perform_measurements
