#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2011 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="wp1-rp-disjointPathsI"
. ./measure-version2

# ###########################################################################
# BESCHREIBUNG:
# Variation der Bandbreite von 2 symmetrischen Pfaden über disjunkte Pfade
# ZIEL:
# Effekt von Resource Pooling zeigen
# ###########################################################################


Run_VALUES="1"
Scenario_VALUES="DisjointPaths"   # !!!
Runtime_VALUES="60"
Flows_VALUES="1"
CompareWithReference_VALUES="true"
ReferenceFlowProtocol_VALUES="SCTP"   # Protokoll fuer Referenzstrom
OnlyOneAssoc_VALUES="true"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1452"
Unordered_VALUES="1.0"   # !!!

SndBuf_VALUES="500000"
RcvBuf_VALUES="250000"
OptionCMT_VALUES="true"
OptionRP_VALUES="false true"
OptionDAC_VALUES="true"
OptionNRSACK_VALUES="false true"   # !!!
OptionBufferSplitting_VALUES="bothSides"   # !!!

# First trail
RateNorthernTrail_VALUES="1000 10000"
DelayNorthernTrail_VALUES="0"
LossNorthernTrail_VALUES="0"
# Second trail
RateSouthernTrail_VALUES="-1"
DelaySouthernTrail_VALUES="-1"
LossSouthernTrail_VALUES="-1"


perform_measurements
