#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2011 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

Directory="test1"
. ./measure-version2


Run_VALUES="1"
Scenario_VALUES="TestLocal"   # !!!
Runtime_VALUES="5"
Flows_VALUES="1"
FrameRate_VALUES="const0"
FrameSize_VALUES="const1444"   # !!!
Unordered_VALUES="1.0"   # !!!
SndBuf_VALUES="300000"
RcvBuf_VALUES="100000"

BidirectionalQoS_VALUES="true"

# First trail
RateNorthernTrail_VALUES="1000 10000"
DelayNorthernTrail_VALUES="1"
LossNorthernTrail_VALUES="0"

# Second trail
RateSouthernTrail_VALUES="-1"
DelaySouthernTrail_VALUES="-1"
LossSouthernTrail_VALUES="-1"


perform_measurements
