.\" ==========================================================================
.\"         _   _      _   ____            __ __  __      _
.\"        | \ | | ___| |_|  _ \ ___ _ __ / _|  \/  | ___| |_ ___ _ __
.\"        |  \| |/ _ \ __| |_) / _ \ '__| |_| |\/| |/ _ \ __/ _ \ '__|
.\"        | |\  |  __/ |_|  __/  __/ |  |  _| |  | |  __/ ||  __/ |
.\"        |_| \_|\___|\__|_|   \___|_|  |_| |_|  |_|\___|\__\___|_|
.\"
.\"                  NetPerfMeter -- Network Performance Meter
.\"                 Copyright (C) 2009-2025 by Thomas Dreibholz
.\" ==========================================================================
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact:  dreibh@simula.no
.\" Homepage: https://www.nntb.no/~dreibh/netperfmeter/
.\"
.\" ###### Setup ############################################################
.Dd October 18, 2024
.Dt runtimeestimator 1
.Os runtimeestimator
.\" ###### Name #############################################################
.Sh NAME
.Nm runtimeestimator
.Nd Batch Job Runtime Estimator
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm runtimeestimator
start_file
total_runs
current_run
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm runtimeestimator
is a simple program to estimate the total runtime of a batch job consisting
of multiple runs. Upon initialisation, it initialises a start file with a
time stamp. Each time a run is completed, it prints out the estimated total
runtime.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments have to be provided:
.Bl -tag -width indent
.It start_file
The name of the start file.
.It total_runs
The total number of runs.
.It current_run
The current run number that has just been completed.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
Some netperfmeter usage examples:
.Bl -tag -width indent
.It runtimeestimator runtime.dat 100 0
Initialize runtime estimation (i.e. before the first run). The start file
"runtime.dat" is created.
.It runtimeestimator runtime.dat 100 1
Completed run 1 of 100 (i.e. the first run).
.It runtimeestimator runtime.dat 100 5
Completed run 5 of 100.
.It runtimeestimator runtime.dat 100 100
Completed run 100 of 100 (i.e. all runs are complete).
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/netperfmeter
.br
mailto://dreibh@simula.no
.br
