#!/bin/bash

HOST_EAST="132.252.153.18"
HOST_WEST="132.252.153.10,132.252.153.138"   # !!! Disjoint Links !!!
# HOST_WEST="132.252.153.10,132.252.153.14"   # !!! Shared Bottleneck !!!
ROUTER_NORTH="132.252.153.9"
NETWORK_NW="132.252.153.8/29"
NETWORK_NE="132.252.153.16/29"
ROUTER_SOUTH="132.252.153.137"
NETWORK_SW="132.252.153.136/29"
NETWORK_SE="132.252.153.144/29"


RateNorthernTrail="10000"
DelayNorthernTrail="10"
LossNorthernTrail="0"
ErrorNorthernTrail="0"
RateSouthernTrail="10000"
DelaySouthernTrail="10"
LossSouthernTrail="0"
ErrorSouthernTrail="0"
BidirectionalQoS="true"


ssh $ROUTER_NORTH ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setqos 1 $NETWORK_NW $NETWORK_NE $RateNorthernTrail $DelayNorthernTrail $LossNorthernTrail $ErrorNorthernTrail $BidirectionalQoS || exit 1
ssh $ROUTER_SOUTH ~/src/netperfmeter/src/rootshell ~/src/netperfmeter/src/setqos 1 $NETWORK_SW $NETWORK_SE $RateSouthernTrail $DelaySouthernTrail $LossSouthernTrail $ErrorSouthernTrail $BidirectionalQoS || exit 1
