#!/bin/sh
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2010 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 [ID] [Source Network] [Destination Network] [Bandwidth in kbit/s] [Delay in ms] [Loss Rate] [Error Rate] [bidirectional]"
   exit 1
fi


# ====== Get parameters =====================================================
ID="$1"
if [ "$2" != "" ] ; then
   NETWORK_SRC="$2"
else
   NETWORK_SRC="0.0.0.0/0"
fi
if [ "$3" != "" ] ; then
   NETWORK_DST="$3"
else
   NETWORK_DST="0.0.0.0/0"
fi
BANDWIDTH=""
DELAY=""
LOSS=""
ERROR=""
addRule=0
bidirectionalQoS=0
if [ "$4" != "" ] ; then
   BANDWIDTH="$4"
   addRule=1
fi
if [  "$5" != "" ] ; then
   DELAY="$5"
   addRule=1
fi
if [ "$6" != "" ] ; then
   LOSS="$6"
   addRule=1
fi
if [ "$7" != "" ] ; then
   ERROR="$7"
   addRule=1
fi
if [ "$8" = "true" -o "$8" = "bidirectional" ] ; then
   bidirectionalQoS=1
fi


# ====== Linux QoS setup ====================================================
SYSTEM=`uname`
if [ "$SYSTEM" = "Linux" ] ; then
   echo "Linux"
   INTERFACES=`eval "ifconfig -a" 2>/dev/null | sed -ne 's|^\('$cur'[^[:space:][:punct:]]\{1,\}\).*$|\1|p'`

   echo "=== Removing old configuration ... =============================="
   for iface in $INTERFACES ; do
      tc qdisc del dev $iface root   # Ohne ID-Angabe wird Root mit jeder ID entfernt!
   done
   if [ $addRule -eq 1 ] ; then
      if [ "$BANDWIDTH" != "" ] ; then
         BANDWIDTH="rate ${BANDWIDTH}kbit"
      fi
      if [ "$DELAY" != "" ] ; then
         DELAY="delay ${DELAY}ms"
      fi
      if [ "$LOSS" != "" ] ; then
         LOSS="loss `./ldcalc ${LOSS} "*" "100.0"`%"
      fi
      if [ "$ERROR" != "" ] ; then
         ERROR="corrupt `./ldcalc ${ERROR} "*" "100.0"`%"
      fi
      for iface in $INTERFACES ; do
         echo "=== Configuring interface $iface ... ========================="
         tc qdisc add dev $iface root handle 9$ID:0 prio
         tc qdisc add dev $iface parent 9$ID:3 handle 8$ID:0 netem $DELAY $LOSS $ERROR
         tc qdisc add dev $iface parent 8$ID:0 handle 7$ID:0 tbf $BANDWIDTH burst 16000 limit 150000
         tc filter add dev $iface protocol ip parent 9$ID:0 prio 3 u32 match ip src $NETWORK_SRC match ip dst $NETWORK_DST flowid 9$ID:3
         tc -s qdisc ls dev $iface
      done
   fi


# ====== FreeBSD QoS setup ==================================================
elif [ "$SYSTEM" = "FreeBSD" ] ; then
   let ID2=$ID+1
   /sbin/ipfw $ID  delete pipe $ID  2>/dev/null   # Delete old configuration
   /sbin/ipfw $ID2 delete pipe $ID2 2>/dev/null   # Delete old configuration
   if [ $addRule -eq 1 ] ; then
      if [ "$BANDWIDTH" != "" ] ; then
         BANDWIDTH="bw ${BANDWIDTH}Kbit/s"
      fi
      if [ "$DELAY" != "" ] ; then
         DELAY="delay ${DELAY}ms"
      fi
      if [ "$LOSS" != "" ] ; then
         LOSS="plr ${LOSS}"
      fi
      if [ "$ERROR" != "" ] ; then
         if [ ! $ERROR -eq 0 ] ; then
            ERROR="ber ${ERROR}"
         else
            ERROR=""
         fi
      fi
      queueParameters="queue 80 red 0.002/20/80/0.02"
      /sbin/ipfw add $ID pipe $ID out src-ip $NETWORK_SRC dst-ip $NETWORK_DST
      /sbin/ipfw pipe $ID config $BANDWIDTH $DELAY $LOSS $ERROR $queueParameters
      if [ $bidirectionalQoS -eq 1 ] ; then
        /sbin/ipfw add $ID2 pipe $ID2 out src-ip $NETWORK_DST dst-ip $NETWORK_SRC
        /sbin/ipfw pipe $ID2 config $BANDWIDTH $DELAY $LOSS $ERROR $queueParameters
      fi
   fi


# ====== Other systems ======================================================
else
   echo >&2 "ERROR: Unsupported system $SYSTEM!"
   exit 1
fi
