#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 [cmt on|off] [dac on|off] [nrsack on|off] [rp on|off]"
   exit 1
fi


# ====== Get parameters =====================================================
CMT=0
DAC=0
NRSACK=0
RP=0

while [ "$1" != "" ] ; do
   if [ "$1" = "cmt" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         CMT=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         CMT=0
      else
         echo >&2 "ERROR: Bad setting for cmt!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "dac" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         DAC=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         DAC=0
      else
         echo >&2 "ERROR: Bad setting for dac!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "nrsack" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         NRSACK=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         NRSACK=0
      else
         echo >&2 "ERROR: Bad setting for nrsack!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "rp" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         RP=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         RP=0
      else
         echo >&2 "ERROR: Bad setting for rp!"
         exit 1
      fi
      shift ; shift

   else
      echo >&2 "ERROR: Unknown setting $1!"
      exit 1
   fi
done


echo "SCTP Configuration:"
echo " - CMT:    $CMT"
echo " - DAC:    $DAC"
echo " - NRSACK: $NRSACK"
echo " - CMT-RP: $RP"


SYSTEM=`uname`
# ====== FreeBSD QoS setup ==================================================
if [ "$SYSTEM" = "FreeBSD" ] ; then
   sysctl net.inet.sctp.cmt_on_off=$CMT
   sysctl net.inet.sctp.cmt_use_dac=$DAC
   sysctl net.inet.sctp.nr_sack_on_off=$NRSACK
   sysctl kern.ipc.maxsockbuf=100005000      # This is the absolute socket buffer limit!
   sysctl net.inet.sctp.sendspace=10000000   # SCTP limit, seems to need full pages!
   sysctl net.inet.sctp.recvspace=10000000   # SCTP limit, seems to need full pages!
   if [ $RP -eq 0 ] ; then
      sysctl net.inet.sctp.default_cc_module=0
   else
      echo "!!!! CMT-RP ist eingeschaltet !!!!"
      sysctl net.inet.sctp.default_cc_module=3
   fi

# ====== Other systems ======================================================
else
   echo >&2 "ERROR: Unsupported system $SYSTEM!"
   exit 1
fi
