#!/bin/bash
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009-2010 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 [cmt on|off] [dac on|off] [nrsack on|off] [rp on|off] [bufferSplitting none|senderOnly|reeiverOnly|bothSides] [initialCwnd SIZE_IN_MTU] [cwndMaxBurst on|off"
   exit 1
fi


# ====== Get parameters =====================================================
CMT=0
DAC=0
NRSACK=0
RP=0
BUFFERSPLITTING=0
INITIAL_CWND=3
CWND_MAXBURST=0

while [ "$1" != "" ] ; do
   if [ "$1" = "cmt" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         CMT=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         CMT=0
      else
         echo >&2 "ERROR: Bad setting for cmt!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "dac" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         DAC=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         DAC=0
      else
         echo >&2 "ERROR: Bad setting for dac!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "nrsack" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         NRSACK=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         NRSACK=0
      else
         echo >&2 "ERROR: Bad setting for nrsack!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "rp" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         RP=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         RP=0
      else
         echo >&2 "ERROR: Bad setting for rp!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "cwndMaxBurst" ] ; then
      if [ "$2" = "on" -o "$2" = "true" ] ; then
         CWND_MAXBURST=1
      elif [ "$2" = "off" -o "$2" = "false" ] ; then 
         CWND_MAXBURST=0
      else
         echo >&2 "ERROR: Bad setting for cwndMaxBurst!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "bufferSplitting" ] ; then
      if [ "$2" = "none" ] ; then
         BUFFERSPLITTING=0
      elif [ "$2" = "senderOnly" ] ; then 
         BUFFERSPLITTING=1
      elif [ "$2" = "receiverOnly" ] ; then 
         BUFFERSPLITTING=2
      elif [ "$2" = "bothSides" ] ; then 
         BUFFERSPLITTING=3
      else
         echo >&2 "ERROR: Bad setting for bufferSplitting!"
         exit 1
      fi
      shift ; shift

   elif [ "$1" = "initialCwnd" ] ; then
      INITIAL_CWND=$2
      shift ; shift

   else
      echo >&2 "ERROR: Unknown setting $1!"
      exit 1
   fi
done


# echo "SCTP Configuration:"
# echo " - CMT:             $CMT"
# echo " - DAC:             $DAC"
# echo " - NRSACK:          $NRSACK"
# echo " - CMT-RP:          $RP"
# echo " - BUFFERSPLITTING: $BUFFERSPLITTING"
# echo " - CWND_MAXBURST:   $CWND_MAXBURST"


SYSTEM=`uname`
# ====== FreeBSD QoS setup ==================================================
if [ "$SYSTEM" = "FreeBSD" ] ; then
   sysctl net.inet.sctp.cmt_on_off=$CMT >/dev/null
   sysctl net.inet.sctp.rp_on_off=$RP >/dev/null
   sysctl net.inet.sctp.cmt_use_dac=$DAC >/dev/null
   sysctl net.inet.sctp.nr_sack_on_off=$NRSACK >/dev/null
   sysctl net.inet.sctp.buffer_splitting=$BUFFERSPLITTING >/dev/null
   sysctl net.inet.sctp.initial_cwnd=$INITIAL_CWND >/dev/null
   sysctl net.inet.sctp.cwnd_maxburst=$CWND_MAXBURST >/dev/null
   sysctl kern.ipc.maxsockbuf=100005000 >/dev/null      # This is the absolute socket buffer limit!
   sysctl net.inet.sctp.sendspace=10000000 >/dev/null   # SCTP limit, seems to need full pages!
   sysctl net.inet.sctp.recvspace=10000000 >/dev/null   # SCTP limit, seems to need full pages!

# ====== Other systems ======================================================
else
   echo >&2 "ERROR: Unsupported system $SYSTEM!"
   exit 1
fi
