#!/bin/sh
# $Id$
#
# Network Performance Meter
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

make -j2 || exit 1

# Disjoint Paths
nohup ./netperfmeter 7010 -verbosity=0 -local=132.252.153.18,89.246.242.230 >server-DisjointPaths.log 2>&1 &

# Shared Bottleneck
nohup ./netperfmeter 7020 -verbosity=0 -local=132.252.153.18,132.252.153.22 >server-SharedBottleneck.log 2>&1 &
