.\" $Id$
.\"
.\" Simple Connectivity Test
.\" Copyright (C) 2015 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd May 29, 2012
.Dt testtool 1
.Os testtool
.\" ###### Name #############################################################
.Sh NAME
.Nm testtool
.Nd Simple Connectivity Test
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm testtool
.Op output_file
.Op udp|sctp
.Op local_address:port
.Op tos
.Op passive
.Op ...
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm testtool
is a simple connectivity test program using UDP or SCTP.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments have to be provided:
.Bl -tag -width indent
.It output_file
Specifies the name of the output file to write. If the suffix of this name is .bz2, the file will be BZip2-compressed on the fly.
.It udp|sctp
Specifies the protocol to be used (UDP or SCTP).
.It local_address:local_port
Specifies the local endpoint address (IPv4/IPv6 as well as transport protocol port).
.It tos
Specifies the Type of Service/Traffic Class for outgoing IP packets.
.It passive
Starts testtool in passive mode, accepting and handling incoming packets.
.It ping:number_of_packets:packet_size:inter_packet_time remote_address:remote_port
Starts ping test (remote side echos packets), with number_of_packets packets in total, inter_packet_time seconds between each two packets and a packet size of packet_size bytes.
.It discard:number_of_packets:packet_size:inter_packet_time remote_address:remote_port
Starts discard test (remote side simply discards packets), with number_of_packets packets in total, inter_packet_time seconds between each two packets and a packet size of packet_size bytes.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
Some testtool usage examples:
.Bl -tag -width indent
.It testtool passive.out udp [::1]:10000 0x48 passive
.It testtool active.out.bz2 udp [::1]:10001 0x28 active [::1]:10000 ping:20:1000:0.1
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
http://simula.no/people/dreibh
.br
mailto://dreibh@simula.no
.br
