#!/bin/sh
# $Id$
#
# Network Performance Meter
# Copyright (C) 2009 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

DIRECTORY=test7a-output
ESSEN=217.91.155.146
BURGSTEINFURT=87.139.124.106
if [ -e $DIRECTORY ] ; then
   rm -rf $DIRECTORY
fi
mkdir $DIRECTORY


# ====== Options ============================================================
LOCAL=$ESSEN
REMOTE=$BURGSTEINFURT
FLOW_SETTINGS="const0:const0:const0:const1452"
VALGRIND=
# VALGRIND="valgrind --tool=helgrind"
# VALGRIND=./debug
# ===========================================================================


make -j2 &&  $VALGRIND ./netperfmeter $REMOTE:9000 \
   "-activenodename=Streaming-Client" \
   "-passivenodename=Streaming-Server" \
   -local=$LOCAL \
   -runtime=900 \
   -verbosity=9 \
   -config=$DIRECTORY/output.config \
   -vector=$DIRECTORY/output.vec.bz2 \
   -scalar=$DIRECTORY/output.sca.bz2 \
   -sctp \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
      $FLOW_SETTINGS \
   $@
